name: compass
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build

    strategy:
      matrix:
        runs-on: [ubuntu-latest, macOS-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: npm run build
